module.exports.jquery = require('jquery')
module.exports.aframe = require('aframe')
module.exports.htmlShader = require('aframe-html-shader')
module.exports.videoControls = require('aframe-video-controls')
module.exports.mouseCursor = require('aframe-mouse-cursor-component')
module.exports.eventSet = require('aframe-event-set-component')